name: "Regenerate Docs & Deploy to GitHub Pages"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SYNC_PAT_CRYPTO_DOCS }}

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and generate package-lock.json
        run: |
          npm install
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Generate documentation
        run: npx typedoc

      - name: Push changes to crypto-core
        run: |
          git clone https://x-access-token:${{ secrets.SYNC_PAT_CRYPTO_DOCS }}@github.com/deepmojo/crypto-core.git temp-repo
          cp -r docs temp-repo/
          cp package-lock.json temp-repo/
          cd temp-repo
          git add docs package-lock.json
          git commit -m "Update docs and package-lock.json" || echo "No changes to commit"
          git push
          cd ..
          rm -rf temp-repo

      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
